# Generated by Django 3.1.5 on 2021-01-23 08:14

import uuid

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "media",
                    models.CharField(
                        choices=[
                            ("Web Novel", "Web Novel"),
                            ("Light Novel", "Light Novel"),
                            ("Comic", "Comic"),
                            ("Cartoon", "Cartoon"),
                        ],
                        max_length=30,
                    ),
                ),
                ("origin", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
